#
# Configuration for eslint, a javascript linter
# Setup to find errors with standardJS but leave formatting to Prettier
#

root: true

parserOptions:
  sourceType: 'module'
  ecmaVersion: 2018

env:
  node: true
  jest: true

extends:
  - standard
  - prettier
  - prettier/standard
