const { join } = require('path')
const { promisify } = require('util')
const fs = require('fs')

const ora = require('ora')
const ms = require('ms')
const Sass = require('sass')
const Yaml = require('yaml')
const Handlebars = require('handlebars')

const readFile = promisify(fs.readFile)
const readdir = promisify(fs.readdir)
const writeFile = promisify(fs.writeFile)
const renderSass = promisify(Sass.render)

const readYaml = async path => Yaml.parse(await readFile(path, 'utf8'))

function makeSass(variables) {
  let sass = ['// Sass variables [autogenerated]', '']

  for (let group in variables) {
    sass.push(...['//', `// ${group}`, '//'])
    for (let variable of variables[group].colors || []) {
      for (let name in variable) {
        sass.push(`$${name}: ${variable[name]}`)
      }
    }
    sass.push('')
  }

  return sass.join('\n')
}

async function registerPartials(base = 'src/partials') {
  for (let file of await readdir(base)) {
    if (!file.endsWith('.html.hbs')) continue

    Handlebars.registerPartial(
      file.replace('.html.hbs', ''),
      await readFile(join(base, file), 'utf8')
    )
  }
}

async function loadData(base = 'src/data') {
  let data = {}
  for (let file of await readdir(base)) {
    if (!file.endsWith('.json')) continue

    Object.assign(data, JSON.parse(await readFile(join(base, file), 'utf8')))
  }
  return data
}

async function renderStyles(variables, base = 'src/styles') {
  let styles = []

  for (let file of await readdir(base)) {
    if (!file.endsWith('.sass')) continue

    let result = await renderSass({
      data: variables + (await readFile(join(base, file), 'utf8')),
      indentedSyntax: true,
      outputStyle: 'compressed'
    })

    styles.push(String(result.css))
  }

  await writeFile(`dist/styles.css`, styles.join(''))
}

async function renderTemplates(data, variables, base = 'src/templates') {
  let templates = await readdir(base)

  let skeleton = Handlebars.compile(
    await readFile('src/skeleton/skeleton.html.hbs', 'utf8')
  )

  let style = await renderSass({
    data: variables + (await readFile('src/skeleton/skeleton.sass', 'utf8')),
    indentedSyntax: true,
    outputStyle: 'compressed'
  })

  await writeFile('dist/skeleton.css', style.css)

  for (let file of templates) {
    if (!file.endsWith('.html.hbs')) continue

    let templateData = await readFile(join(base, file), 'utf8')

    await writeFile(
      join('dist', file.replace('.html.hbs', '.html')),
      skeleton({
        content: Handlebars.compile(templateData)(data),
        templates: templates.map(t => t.replace('.html.hbs', ''))
      })
    )
  }
}

;(async () => {
  const startTime = Date.now()
  const spinner = ora().start('Building')

  try {
    const data = await loadData()

    data.variables = await readYaml('src/variables.yml')

    await registerPartials()

    const sass = makeSass(data.variables)

    await writeFile('dist/variables.sass', sass)

    await renderStyles(sass)

    await renderTemplates(data, sass)

    const duration = ms(Date.now() - startTime)
    spinner.succeed(`Built in ${duration}`)
  } catch (error) {
    spinner.fail(error.message)
    console.log(error.stack)
  }
})()
